# Generated by Django 4.2 on 2024-07-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_contacto_mensaje_cifrado_proyecto_link_repositorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje_cifrado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='link_repositorio',
            field=models.URLField(),
        ),
    ]
